language: ruby
services:
  - mysql
cache: bundler
before_script:
  - gem update --remote bundler
  - gem update --system
  - mv config/database.yml config/database.yml.old
  - cp config/database.yml.ci config/database.yml
  - RAILS_ENV=test bin/rails db:create db:schema:load
script:
  - bin/rails test
  - bundle exec codeclimate-test-reporter
install: bundle install
